services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 123456abc
      POSTGRES_USER: cody
      POSTGRES_DB: timetrackerdb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./dbdata:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
    
  api:  
    build: 
      context: ./TimeTrackerAPI
    restart: always
    environment:
      - DOTNET_DATABASE_STRING=Host=db;Database=timetrackerdb;Username=cody;Password=123456abc;
    depends_on:
      - db
    ports:
      - 4100:8080

