services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 123456abc
      POSTGRES_USER: cody
      POSTGRES_DB: timetrackerdb
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    
  # api:  
  #   build: 
  #     context: ./Project_8.API
  #   environment:
  #     - DOTNET_DATABASE_STRING=user=cody;password=123456abc;host=db;database=timetrackerdb;
  #   links: 
  #     - db:database
  #   depends_on:
  #     - db
  #   ports:
  #     - 4100:7050

